- name: cp {{node_name}} package to node
  copy: src={{package_path}}/Code/{{node_name}}.tar.gz dest={{install_root_path}}/ owner={{ssh_user}} group={{ssh_group}} mode=0640

- name: untar {{node_name}} package
  shell: tar -zxf {{install_root_path}}/{{node_name}}.tar.gz -C {{install_root_path}}/

- name: stop all match service
  shell: supervisorctl stop all

- name: backup {{node_name}} old version
  shell: mv {{node_name}} {{node_name}}.bak.`date +%m%d` chdir={{install_root_path}}/jobs/

- name: install {{node_name}} new version
  shell: mv {{install_root_path}}/{{node_name}} {{install_root_path}}/jobs/

- name: rsync match new version
  shell: bash rsync.sh chdir={{install_root_path}}/jobs/

- name: start engine service
  shell: supervisorctl start all

- name: clean package
  shell: rm -rf {{install_root_path}}/*.tar.gz

- name: print result
  debug: msg="{{node_name}} upgrade sucessful"